// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCah4BsT7Oi6EXCwGOH1LV-jqQJe-5nZ_U',
    appId: '1:1043136268431:web:bcecb6e09225cec69048fa',
    messagingSenderId: '1043136268431',
    projectId: 'test-login-b3d22',
    authDomain: 'test-login-b3d22.firebaseapp.com',
    storageBucket: 'test-login-b3d22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwm7AZFMlHvuVsWVNaxuX3IPwHaOCTn8U',
    appId: '1:1043136268431:android:eeb79701e504dec69048fa',
    messagingSenderId: '1043136268431',
    projectId: 'test-login-b3d22',
    storageBucket: 'test-login-b3d22.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCah4BsT7Oi6EXCwGOH1LV-jqQJe-5nZ_U',
    appId: '1:1043136268431:web:2ba2dc491bb184989048fa',
    messagingSenderId: '1043136268431',
    projectId: 'test-login-b3d22',
    authDomain: 'test-login-b3d22.firebaseapp.com',
    storageBucket: 'test-login-b3d22.firebasestorage.app',
  );
}
